### ISSUE TITLE
failed to install in China

### ISSUE THREAD

**Issue by pahud** [canonical/eks-snap#16]
`snap install eks` fails in China and It keeps failing to get the `pause` image.

http://canonical/eks-snap

https://github.com/canonical/eks-snap/blob/f6cef362a42ccbac56c4f3aa9670a561bab6dcf3/microk8s-resources/default-args/containerd-template.toml#L30

Is it possible to override this `sandbox_image` argument with another custom image to get it around?

<img width="1882" alt="WX20210125-155830@2x" src="https://user-images.githubusercontent.com/278432/105676959-39ea8980-5f26-11eb-9b36-02d94ebf36ed.png">

# eks inspect

```
# eks inspect
Inspecting Certificates
Inspecting services
  Service snap.eks.daemon-cluster-agent is running
  Service snap.eks.daemon-containerd is running
  Service snap.eks.daemon-apiserver is running
  Service snap.eks.daemon-apiserver-kicker is running
  Service snap.eks.daemon-control-plane-kicker is running
  Service snap.eks.daemon-proxy is running
  Service snap.eks.daemon-kubelet is running
  Service snap.eks.daemon-scheduler is running
  Service snap.eks.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
/snap/eks/3/inspect.sh: line 285: store_juju_info: command not found
Inspecting kubeflow
/snap/eks/3/inspect.sh: line 288: store_kubeflow_info: command not found

Building the report tarball
  Report tarball is at /var/snap/eks/3/inspection-report-20210125_075140.tar.gz
  ```

**Comment by ktsakalozos** [comment]
Hi @pahud.

You can edit `/var/snap/eks/current/args/containerd-template.toml` and update the `sandbox_image`  with the pause image appropriate for your case. Then you should restart the snap with `sudo eks.stop` and `sudo eks.start`.

We would be changing the pause container soon to `public.ecr.aws/eks-distro/kubernetes/pause:v1.18.9-eks-1-18-1` . We will however need to push the rest of our images (eg calico cni) to a registry that is available within China. Any recommendations there?

**Comment by pahud** [comment]
Hi, 

China can access `public.ecr.aws` with no issue. Please upload all images to public ecr whenever possible.

I am the maintainer of cdk-eksdistro and this cdk library leverages `eks snap` under the hood. Would be great to see the pause container moving to public ecr so we can close https://github.com/pahud/cdk-eksdistro/issues/2

Thanks.
