### ISSUE TITLE
installation not allowed by "kubernetes-support" plug rule

### ISSUE THREAD

**Issue by tonyiams** [canonical/eks-snap#22]
Hello,

I am trying to install the EKS-D snap on Ubuntu 20.04.2 LTS, and I am getting this error message:

error: cannot perform the following tasks:
- Mount snap "eks" (5) (installation not allowed by "kubernetes-support" plug rule of interface "kubernetes-support")

I first installed snaps for both Docker and MicroK8s in the OS, and then ran this command:

    sudo snap install eks --classic --edge

I tried this in a Ubuntu 20.04.2 LT instance in Google Cloud Platform, as well as in a VM on Oracle VirtualBox, and get the same results.

Here is the output of 'microk8s inspect'.
[inspection-report-20210213_175213.tar.gz](https://github.com/canonical/eks-snap/files/5976225/inspection-report-20210213_175213.tar.gz)

Is there anything else I need to do before installing the EKS-D snap?

Thanks,

Tony Iams

**Comment by youwalther65** [comment]
I have the same issue on Ubuntu 18.04 LTS. Installation worked some weeks ago but now same error.
Using for example microk8s channel 1.20 just succeeds without problems.

**Comment by ktsakalozos** [comment]
@youwalther65 @tonyespy appologies for the inconvenience. This plugin is for work that is about to be released. I have reverted this change. You should be able to deploy the snap now.
