### ISSUE TITLE
Kubernetes 1.19 or 1.20

### ISSUE THREAD

**Issue by mcolladoio** [canonical/eks-snap#23]
It’s not an issue itself, but I’d like to know if would be possible to setup an EKS cluster with Kubernetes version 1.19 or 1.20. 

Actually EKS-D installed on Ubuntu 20.04.

**Comment by ktsakalozos** [comment]
Hi @mcolladoio 

The eks snap packages and releases the eks-d k8s distribution. At this point the eks-d project has done one release of the 1.18 upstream kubernetes, see [1].

If you want to get a similar experience to what the eks snap offers you can `snap install microk8s --classic --channel=<1.19 or 1.20>/stable`. Remember to snap remove eks first.

[1] https://github.com/aws/eks-distro/releases

**Comment by mcolladoio** [comment]
Thanks for your reply @ktsakalozos ! Given that information I'll close the issue.
