### ISSUE TITLE
Build failure raft/uv.h: No such file or directory on arm64 ?

### ISSUE THREAD

**Issue by awsandy** [canonical/eks-snap#24]
Hi 

I have a t4g instance in AWS (Graviton2 arm64) running ubuntu-focal-20.04-arm64-server 

root@ip-172-31-27-168:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

And I've done:

snap install snapcraft --classic
git clone https://github.com/canonical/eks-snap.git
cd eks-snap

snapcraft --use-lxd

runs for while - but errors out with:

  CC       src/server.lo
  CC       src/stmt.lo
In file included from src/server.c:1:0:
src/server.h:2:21: fatal error: raft/uv.h: No such file or directory
compilation terminated.
Makefile:1163: recipe for target 'src/server.lo' failed
make: *** [src/server.lo] Error 1
make: *** Waiting for unfinished jobs....
Failed to run 'make -j2' for 'dqlite': Exited with code 2.
Verify that the part is using the correct parameters and try again.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.

Any suggestions ?

**Comment by ktsakalozos** [comment]
Hi @awsandy. Indeed dqlite changed the libuv dependency to a version not available in the current repositories.

With the PR above we build libuv in the snap. We should merge this fix soon.

Thank you for reporting this.
